version: '2.4'

services: 
  iris:
    build: 
      context: .
    ports:
      - 1972:1972
      - 52773:52773
    environment:
    - TZ=JST-9

    volumes:
      - ./src:/home/irisowner/srcext    

    cap_add:
      - IPC_LOCK