services: 
  iris:
    build: 
      context: .
    ports:
      - 1972:1972
      - 52773:52773
    environment:
    - TZ=JST-9

    volumes:
      - ./src:/home/irisowner/srcext    

    cap_add:
      - IPC_LOCK

    # enable core file
    ulimits:
       core:
        soft: -1
        hard: -1
