ROUTINE TestRoutine
	Set ^calltest=$ZDATETIME($H)
	Quit
Entry() public  {
	Set ^calltest(1)=$ZDATETIME($H)
	Quit
}

Entry1(str,int) public  {
	Set ^calltest(2)=$ZDATETIME($H)_";"_str_";"_int
	Quit 123
}
Entry1a(str,int) public  {
	Set ^calltest(2)=$ZDATETIME($H)_";"_str_";"_int
	Quit 2**62  ;4611686018427387904
}
Entry2(str) public  {
	Set ^calltest(3)=$ZDATETIME($H)_";"_str
	Quit "abcdefg"
}

Entry4() [MYLOCALVAR] public {
	Quit MYLOCALVAR
}

ErrorEntry() public  {
	Set a=1/0
	Quit
}